run:
	go build -o build/parser
	./build/parser -filePath=/Users/rase/dev/computer-enhance-part-2/haversine_generator/build/output/JsonOutput_10.json

run2:
	go build -o build/parser
	./build/parser -filePath=/Users/rase/dev/computer-enhance-part-2/json_parser/test_json.json



